
-- Supprimer les données existantes pour les remplacer par une liste complète
DELETE FROM public.villes;
DELETE FROM public.pays;

-- Ajouter la colonne indicatif téléphonique
ALTER TABLE public.pays ADD COLUMN IF NOT EXISTS indicatif_tel VARCHAR(10);

-- Insérer une liste complète des pays du monde avec leurs indicatifs
INSERT INTO public.pays (nom, code_iso, indicatif_tel) VALUES
('Afghanistan', 'AF', '+93'),
('Afrique du Sud', 'ZA', '+27'),
('Albanie', 'AL', '+355'),
('Algérie', 'DZ', '+213'),
('Allemagne', 'DE', '+49'),
('Andorre', 'AD', '+376'),
('Angola', 'AO', '+244'),
('Antigua-et-Barbuda', 'AG', '+1'),
('Arabie saoudite', 'SA', '+966'),
('Argentine', 'AR', '+54'),
('Arménie', 'AM', '+374'),
('Australie', 'AU', '+61'),
('Autriche', 'AT', '+43'),
('Azerbaïdjan', 'AZ', '+994'),
('Bahamas', 'BS', '+1'),
('Bahreïn', 'BH', '+973'),
('Bangladesh', 'BD', '+880'),
('Barbade', 'BB', '+1'),
('Bélarus', 'BY', '+375'),
('Belgique', 'BE', '+32'),
('Belize', 'BZ', '+501'),
('Bénin', 'BJ', '+229'),
('Bhoutan', 'BT', '+975'),
('Bolivie', 'BO', '+591'),
('Bosnie-Herzégovine', 'BA', '+387'),
('Botswana', 'BW', '+267'),
('Brésil', 'BR', '+55'),
('Brunei', 'BN', '+673'),
('Bulgarie', 'BG', '+359'),
('Burkina Faso', 'BF', '+226'),
('Burundi', 'BI', '+257'),
('Cambodge', 'KH', '+855'),
('Cameroun', 'CM', '+237'),
('Canada', 'CA', '+1'),
('Cap-Vert', 'CV', '+238'),
('Chili', 'CL', '+56'),
('Chine', 'CN', '+86'),
('Chypre', 'CY', '+357'),
('Colombie', 'CO', '+57'),
('Comores', 'KM', '+269'),
('Congo', 'CG', '+242'),
('Congo (RDC)', 'CD', '+243'),
('Corée du Nord', 'KP', '+850'),
('Corée du Sud', 'KR', '+82'),
('Costa Rica', 'CR', '+506'),
('Côte d''Ivoire', 'CI', '+225'),
('Croatie', 'HR', '+385'),
('Cuba', 'CU', '+53'),
('Danemark', 'DK', '+45'),
('Djibouti', 'DJ', '+253'),
('Dominique', 'DM', '+1'),
('Égypte', 'EG', '+20'),
('Émirats arabes unis', 'AE', '+971'),
('Équateur', 'EC', '+593'),
('Érythrée', 'ER', '+291'),
('Espagne', 'ES', '+34'),
('Estonie', 'EE', '+372'),
('Eswatini', 'SZ', '+268'),
('États-Unis', 'US', '+1'),
('Éthiopie', 'ET', '+251'),
('Fidji', 'FJ', '+679'),
('Finlande', 'FI', '+358'),
('France', 'FR', '+33'),
('Gabon', 'GA', '+241'),
('Gambie', 'GM', '+220'),
('Géorgie', 'GE', '+995'),
('Ghana', 'GH', '+233'),
('Grèce', 'GR', '+30'),
('Grenade', 'GD', '+1'),
('Guatemala', 'GT', '+502'),
('Guinée', 'GN', '+224'),
('Guinée-Bissau', 'GW', '+245'),
('Guinée équatoriale', 'GQ', '+240'),
('Guyana', 'GY', '+592'),
('Haïti', 'HT', '+509'),
('Honduras', 'HN', '+504'),
('Hongrie', 'HU', '+36'),
('Îles Cook', 'CK', '+682'),
('Îles Marshall', 'MH', '+692'),
('Îles Salomon', 'SB', '+677'),
('Inde', 'IN', '+91'),
('Indonésie', 'ID', '+62'),
('Irak', 'IQ', '+964'),
('Iran', 'IR', '+98'),
('Irlande', 'IE', '+353'),
('Islande', 'IS', '+354'),
('Israël', 'IL', '+972'),
('Italie', 'IT', '+39'),
('Jamaïque', 'JM', '+1'),
('Japon', 'JP', '+81'),
('Jordanie', 'JO', '+962'),
('Kazakhstan', 'KZ', '+7'),
('Kenya', 'KE', '+254'),
('Kirghizistan', 'KG', '+996'),
('Kiribati', 'KI', '+686'),
('Koweït', 'KW', '+965'),
('Laos', 'LA', '+856'),
('Lesotho', 'LS', '+266'),
('Lettonie', 'LV', '+371'),
('Liban', 'LB', '+961'),
('Liberia', 'LR', '+231'),
('Libye', 'LY', '+218'),
('Liechtenstein', 'LI', '+423'),
('Lituanie', 'LT', '+370'),
('Luxembourg', 'LU', '+352'),
('Madagascar', 'MG', '+261'),
('Malaisie', 'MY', '+60'),
('Malawi', 'MW', '+265'),
('Maldives', 'MV', '+960'),
('Mali', 'ML', '+223'),
('Malte', 'MT', '+356'),
('Maroc', 'MA', '+212'),
('Maurice', 'MU', '+230'),
('Mauritanie', 'MR', '+222'),
('Mexique', 'MX', '+52'),
('Micronésie', 'FM', '+691'),
('Moldavie', 'MD', '+373'),
('Monaco', 'MC', '+377'),
('Mongolie', 'MN', '+976'),
('Monténégro', 'ME', '+382'),
('Mozambique', 'MZ', '+258'),
('Myanmar', 'MM', '+95'),
('Namibie', 'NA', '+264'),
('Nauru', 'NR', '+674'),
('Népal', 'NP', '+977'),
('Nicaragua', 'NI', '+505'),
('Niger', 'NE', '+227'),
('Nigeria', 'NG', '+234'),
('Niue', 'NU', '+683'),
('Norvège', 'NO', '+47'),
('Nouvelle-Zélande', 'NZ', '+64'),
('Oman', 'OM', '+968'),
('Ouganda', 'UG', '+256'),
('Ouzbékistan', 'UZ', '+998'),
('Pakistan', 'PK', '+92'),
('Palaos', 'PW', '+680'),
('Palestine', 'PS', '+970'),
('Panama', 'PA', '+507'),
('Papouasie-Nouvelle-Guinée', 'PG', '+675'),
('Paraguay', 'PY', '+595'),
('Pays-Bas', 'NL', '+31'),
('Pérou', 'PE', '+51'),
('Philippines', 'PH', '+63'),
('Pologne', 'PL', '+48'),
('Portugal', 'PT', '+351'),
('Qatar', 'QA', '+974'),
('République centrafricaine', 'CF', '+236'),
('République dominicaine', 'DO', '+1'),
('République tchèque', 'CZ', '+420'),
('Roumanie', 'RO', '+40'),
('Royaume-Uni', 'GB', '+44'),
('Russie', 'RU', '+7'),
('Rwanda', 'RW', '+250'),
('Saint-Christophe-et-Niévès', 'KN', '+1'),
('Saint-Marin', 'SM', '+378'),
('Saint-Vincent-et-les-Grenadines', 'VC', '+1'),
('Sainte-Lucie', 'LC', '+1'),
('Salvador', 'SV', '+503'),
('Samoa', 'WS', '+685'),
('São Tomé-et-Príncipe', 'ST', '+239'),
('Sénégal', 'SN', '+221'),
('Serbie', 'RS', '+381'),
('Seychelles', 'SC', '+248'),
('Sierra Leone', 'SL', '+232'),
('Singapour', 'SG', '+65'),
('Slovaquie', 'SK', '+421'),
('Slovénie', 'SI', '+386'),
('Somalie', 'SO', '+252'),
('Soudan', 'SD', '+249'),
('Soudan du Sud', 'SS', '+211'),
('Sri Lanka', 'LK', '+94'),
('Suède', 'SE', '+46'),
('Suisse', 'CH', '+41'),
('Suriname', 'SR', '+597'),
('Syrie', 'SY', '+963'),
('Tadjikistan', 'TJ', '+992'),
('Tanzanie', 'TZ', '+255'),
('Tchad', 'TD', '+235'),
('Thaïlande', 'TH', '+66'),
('Timor oriental', 'TL', '+670'),
('Togo', 'TG', '+228'),
('Tonga', 'TO', '+676'),
('Trinité-et-Tobago', 'TT', '+1'),
('Tunisie', 'TN', '+216'),
('Turkménistan', 'TM', '+993'),
('Turquie', 'TR', '+90'),
('Tuvalu', 'TV', '+688'),
('Ukraine', 'UA', '+380'),
('Uruguay', 'UY', '+598'),
('Vanuatu', 'VU', '+678'),
('Vatican', 'VA', '+39'),
('Venezuela', 'VE', '+58'),
('Vietnam', 'VN', '+84'),
('Yémen', 'YE', '+967'),
('Zambie', 'ZM', '+260'),
('Zimbabwe', 'ZW', '+263');

-- Ajouter quelques villes pour les pays principaux
INSERT INTO public.villes (nom, pays_id, code_postal) 
SELECT v.nom, p.id, v.code_postal
FROM (VALUES 
  -- France
  ('Paris', 'FR', '75000'),
  ('Lyon', 'FR', '69000'),
  ('Marseille', 'FR', '13000'),
  ('Toulouse', 'FR', '31000'),
  ('Nice', 'FR', '06000'),
  ('Nantes', 'FR', '44000'),
  ('Strasbourg', 'FR', '67000'),
  ('Montpellier', 'FR', '34000'),
  ('Bordeaux', 'FR', '33000'),
  ('Lille', 'FR', '59000'),
  -- Belgique
  ('Bruxelles', 'BE', '1000'),
  ('Anvers', 'BE', '2000'),
  ('Gand', 'BE', '9000'),
  ('Liège', 'BE', '4000'),
  -- Suisse
  ('Zurich', 'CH', '8000'),
  ('Genève', 'CH', '1200'),
  ('Bâle', 'CH', '4000'),
  ('Berne', 'CH', '3000'),
  -- Canada
  ('Toronto', 'CA', 'M5H'),
  ('Montréal', 'CA', 'H3A'),
  ('Vancouver', 'CA', 'V6B'),
  ('Ottawa', 'CA', 'K1A'),
  -- Maroc
  ('Casablanca', 'MA', '20000'),
  ('Rabat', 'MA', '10000'),
  ('Marrakech', 'MA', '40000'),
  ('Fès', 'MA', '30000')
) AS v(nom, code_pays, code_postal)
JOIN public.pays p ON p.code_iso = v.code_pays;
