
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlmiuwwfxerrinfthvrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhsbWl1d3dmeGVycmluZnRodnJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MDE5NjQsImV4cCI6MjA2NTE3Nzk2NH0.KN8vcjCrAWo7YUqkHi7j8pk-g7MROe_EsWqOvQ5ylfM";

// Déterminer le domaine approprié pour les cookies
const getDomainForCookies = () => {
  const hostname = window.location.hostname;
  
  // En développement local
  if (hostname === 'localhost' || hostname === '127.0.0.1') {
    return 'localhost';
  }
  
  // Pour les domaines Lovable (lovableproject.com)
  if (hostname.includes('lovableproject.com')) {
    return '.lovableproject.com';
  }
  
  // Pour d'autres domaines de développement
  if (hostname.includes('.local') || hostname.includes('127.0.0.1')) {
    return hostname;
  }
  
  // Pour la production, utiliser le domaine racine
  const parts = hostname.split('.');
  if (parts.length > 2) {
    return '.' + parts.slice(-2).join('.');
  }
  
  return hostname;
};

// Configuration des options d'authentification avec gestion des cookies
const authOptions = {
  storage: window.localStorage,
  autoRefreshToken: true,
  persistSession: true,
  detectSessionInUrl: true,
  flowType: 'pkce' as const,
  // Configuration des cookies pour éviter les erreurs de domaine
  cookieOptions: {
    name: 'supabase-auth-token',
    lifetime: 60 * 60 * 24 * 7, // 7 jours
    domain: getDomainForCookies(),
    path: '/',
    sameSite: 'lax' as const,
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: authOptions
  }
);

// Debug: afficher la configuration des cookies en mode développement
if (import.meta.env.DEV) {
  console.log('🔧 Configuration Supabase:', {
    hostname: window.location.hostname,
    cookieDomain: getDomainForCookies(),
    authOptions: authOptions
  });
}
