// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlmiuwwfxerrinfthvrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhsbWl1d3dmeGVycmluZnRodnJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MDE5NjQsImV4cCI6MjA2NTE3Nzk2NH0.KN8vcjCrAWo7YUqkHi7j8pk-g7MROe_EsWqOvQ5ylfM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);